
import { useState } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import AppLayout from '@/components/AppLayout';
import { toast } from '@/hooks/use-toast';
import { ArrowUpRight, Copy, Mail, Share2 } from 'lucide-react';

const ReferPage = () => {
  const [email, setEmail] = useState('');
  const [isSending, setIsSending] = useState(false);
  
  // This would be generated by the backend in a real app
  const referralCode = "SWIFTBANK2025";
  const referralLink = `https://swiftbank.com/register?ref=${referralCode}`;
  
  const handleCopyLink = () => {
    navigator.clipboard.writeText(referralLink);
    toast({
      title: "Link Copied",
      description: "Referral link copied to clipboard",
    });
  };
  
  const handleCopyCode = () => {
    navigator.clipboard.writeText(referralCode);
    toast({
      title: "Code Copied",
      description: "Referral code copied to clipboard",
    });
  };
  
  const handleSendEmail = () => {
    if (!email) return;
    
    setIsSending(true);
    
    // Simulating API call
    setTimeout(() => {
      setIsSending(false);
      setEmail('');
      
      toast({
        title: "Email Sent",
        description: "Referral email has been sent successfully",
      });
    }, 1000);
  };
  
  return (
    <AppLayout>
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <h1 className="text-2xl font-bold mb-6">Refer and Earn</h1>
        
        {/* Hero Card */}
        <Card className="bg-gradient-to-r from-purple-600 to-blue-500 text-white mb-8">
          <CardHeader>
            <CardTitle className="text-2xl">Invite friends, earn rewards</CardTitle>
            <CardDescription className="text-white/80">
              Earn 100 points for each friend who joins using your referral
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="text-center">
              <div className="text-5xl font-bold">100</div>
              <div className="text-lg">points per referral</div>
            </div>
            
            <div className="flex items-center justify-center space-x-2 text-sm">
              <div className="flex items-center">
                <ArrowUpRight className="w-4 h-4 mr-1" />
                <span>Share Link</span>
              </div>
              <div className="w-1 h-1 rounded-full bg-white/50"></div>
              <div className="flex items-center">
                <Mail className="w-4 h-4 mr-1" />
                <span>Send Email</span>
              </div>
              <div className="w-1 h-1 rounded-full bg-white/50"></div>
              <div className="flex items-center">
                <Share2 className="w-4 h-4 mr-1" />
                <span>Share Code</span>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Share Card */}
          <Card className="shadow-md">
            <CardHeader>
              <CardTitle className="text-xl">Share Your Referral</CardTitle>
              <CardDescription>Share your unique referral code with friends</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <p className="text-sm font-medium">Your Referral Link</p>
                <div className="flex">
                  <Input 
                    value={referralLink}
                    readOnly 
                    className="rounded-r-none focus-visible:ring-0 bg-gray-50" 
                  />
                  <Button 
                    onClick={handleCopyLink} 
                    className="rounded-l-none"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
              </div>
              
              <div className="space-y-2">
                <p className="text-sm font-medium">Your Referral Code</p>
                <div className="flex">
                  <Input 
                    value={referralCode} 
                    readOnly 
                    className="rounded-r-none focus-visible:ring-0 bg-gray-50" 
                  />
                  <Button 
                    onClick={handleCopyCode} 
                    className="rounded-l-none"
                  >
                    <Copy className="w-4 h-4" />
                  </Button>
                </div>
              </div>
              
              <div className="space-y-2 pt-2">
                <p className="text-sm font-medium">Send Referral Email</p>
                <div className="flex">
                  <Input 
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="friend@example.com" 
                    className="rounded-r-none" 
                  />
                  <Button 
                    onClick={handleSendEmail} 
                    disabled={!email || isSending}
                    className="rounded-l-none flex items-center"
                  >
                    {isSending ? (
                      <>
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                        Sending
                      </>
                    ) : (
                      <>
                        <Mail className="w-4 h-4 mr-2" /> 
                        Send
                      </>
                    )}
                  </Button>
                </div>
              </div>
              
              <div className="flex space-x-4 justify-center pt-2">
                <Button variant="outline" className="flex-1 flex items-center justify-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                  </svg>
                  Facebook
                </Button>
                <Button variant="outline" className="flex-1 flex items-center justify-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
                  </svg>
                  Twitter
                </Button>
                <Button variant="outline" className="flex-1 flex items-center justify-center">
                  <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 448 512" xmlns="http://www.w3.org/2000/svg">
                    <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"></path>
                  </svg>
                  Instagram
                </Button>
              </div>
            </CardContent>
          </Card>
          
          {/* How It Works Card */}
          <Card className="shadow-md">
            <CardHeader>
              <CardTitle className="text-xl">How It Works</CardTitle>
              <CardDescription>Simple steps to earn through referrals</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-6">
                <div className="flex items-start gap-4">
                  <div className="flex items-center justify-center w-8 h-8 rounded-full bg-bank-primary text-white font-bold">
                    1
                  </div>
                  <div>
                    <h3 className="font-medium">Share Your Referral</h3>
                    <p className="text-sm text-gray-600">Share your unique referral code or link with friends and family.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <div className="flex items-center justify-center w-8 h-8 rounded-full bg-bank-primary text-white font-bold">
                    2
                  </div>
                  <div>
                    <h3 className="font-medium">Friend Signs Up</h3>
                    <p className="text-sm text-gray-600">Your friend creates an account using your referral code or link.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <div className="flex items-center justify-center w-8 h-8 rounded-full bg-bank-primary text-white font-bold">
                    3
                  </div>
                  <div>
                    <h3 className="font-medium">Earn Rewards</h3>
                    <p className="text-sm text-gray-600">Both you and your friend receive points when they complete registration.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <div className="flex items-center justify-center w-8 h-8 rounded-full bg-bank-primary text-white font-bold">
                    4
                  </div>
                  <div>
                    <h3 className="font-medium">Redeem Points</h3>
                    <p className="text-sm text-gray-600">Redeem your points for exclusive rewards in the rewards section.</p>
                  </div>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button variant="outline" className="w-full" onClick={() => window.location.href = '/rewards'}>
                View Available Rewards
              </Button>
            </CardFooter>
          </Card>
        </div>
        
        {/* Referral Status */}
        <Card className="mt-8 shadow-md">
          <CardHeader>
            <CardTitle className="text-xl">Your Referral Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              <div className="flex flex-wrap justify-between items-center gap-4">
                <div>
                  <p className="text-sm text-gray-500">Total Referrals</p>
                  <p className="text-3xl font-bold">5</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500">Points Earned</p>
                  <p className="text-3xl font-bold">500</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500">Pending Referrals</p>
                  <p className="text-3xl font-bold">2</p>
                </div>
              </div>
              
              <div className="overflow-x-auto">
                <table className="min-w-full">
                  <thead>
                    <tr className="bg-gray-50 text-left">
                      <th className="px-4 py-2 text-sm font-medium text-gray-600">Name</th>
                      <th className="px-4 py-2 text-sm font-medium text-gray-600">Date</th>
                      <th className="px-4 py-2 text-sm font-medium text-gray-600">Status</th>
                      <th className="px-4 py-2 text-sm font-medium text-gray-600">Points</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    <tr>
                      <td className="px-4 py-2">John Doe</td>
                      <td className="px-4 py-2 text-sm text-gray-500">May 15, 2023</td>
                      <td className="px-4 py-2"><span className="px-2 py-1 rounded text-xs bg-green-100 text-green-800">Completed</span></td>
                      <td className="px-4 py-2 font-medium">100</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-2">Jane Smith</td>
                      <td className="px-4 py-2 text-sm text-gray-500">May 10, 2023</td>
                      <td className="px-4 py-2"><span className="px-2 py-1 rounded text-xs bg-green-100 text-green-800">Completed</span></td>
                      <td className="px-4 py-2 font-medium">100</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-2">Mike Johnson</td>
                      <td className="px-4 py-2 text-sm text-gray-500">May 5, 2023</td>
                      <td className="px-4 py-2"><span className="px-2 py-1 rounded text-xs bg-green-100 text-green-800">Completed</span></td>
                      <td className="px-4 py-2 font-medium">100</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-2">Sarah Williams</td>
                      <td className="px-4 py-2 text-sm text-gray-500">May 2, 2023</td>
                      <td className="px-4 py-2"><span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">Pending</span></td>
                      <td className="px-4 py-2 font-medium">0</td>
                    </tr>
                    <tr>
                      <td className="px-4 py-2">David Brown</td>
                      <td className="px-4 py-2 text-sm text-gray-500">May 1, 2023</td>
                      <td className="px-4 py-2"><span className="px-2 py-1 rounded text-xs bg-yellow-100 text-yellow-800">Pending</span></td>
                      <td className="px-4 py-2 font-medium">0</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
};

export default ReferPage;
